[package]
name = "rustoculuslogger"
version = "0.1.0"
authors = ["Caleb McCarthy <caleb.andrew.mccarthy@ibm.com>"]
edition = "2018"

[dependencies]
chrono = "0.4"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"